// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a7TAS5D5YXQzv692CQ5xSD
// Component: hSS7-YPNMS
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Discord from "../../Discord"; // plasmic-import: rCy3GbArI5/component
import Twitter from "../../Twitter"; // plasmic-import: ymGsLy5iOY/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 20PVpOcfZek/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_gzilla.module.css"; // plasmic-import: a7TAS5D5YXQzv692CQ5xSD/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: hSS7-YPNMS/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: AgW1UYarLz/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: cdZsNMb-WaV/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: AOhC70hsnT7/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: N4WDnrBqw/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: IVftXjyc0km/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: v0NAqs69JiF/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: o4vthOQ1Qo7/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: M7j_eC1FIeT/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: XyJq-zU79E/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: XV3v1go3yG/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: stY3m5WqWoG/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: zQS6-DCym6_/icon
import Group8Icon from "./icons/PlasmicIcon__Group8"; // plasmic-import: tUJpRi474u/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: PknH7KtG-m/icon
import Group866Icon from "./icons/PlasmicIcon__Group866"; // plasmic-import: 33jHc5DmFk/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: JrNwuesiFLb/icon
import Ellipse5Icon from "./icons/PlasmicIcon__Ellipse5"; // plasmic-import: mTBKZbtRjDC/icon
import Group10Icon from "./icons/PlasmicIcon__Group10"; // plasmic-import: OvkHwZCXIuE/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: -AmghSp2nYW/icon
import Line8Icon from "./icons/PlasmicIcon__Line8"; // plasmic-import: xXRT2qfkxG/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: KGvJ6UR6dRr/icon
import Group12Icon from "./icons/PlasmicIcon__Group12"; // plasmic-import: A5zQ3tPYW-z/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: By3s_2O-sUJ/icon
import Group13Icon from "./icons/PlasmicIcon__Group13"; // plasmic-import: qLQHf2BpYnO/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: Vo6fmg67qf8/icon
import group26SdBYfIbR5H from "./images/group2.svg"; // plasmic-import: 6SdBYfIbR5h/picture
import group5M3ESpiRigix from "./images/group5.svg"; // plasmic-import: M3eSpiRigix/picture
import group7Z1Vvgga4LAr from "./images/group7.svg"; // plasmic-import: Z1Vvgga4lAR/picture
import group9Yl7EDl7Rtt from "./images/group9.svg"; // plasmic-import: YL7eDL7RTT/picture
import group11JnCwAzfbeiS from "./images/group11.svg"; // plasmic-import: JNCwAzfbeiS/picture
import group14ExUhI5YgXor from "./images/group14.svg"; // plasmic-import: ExUhI5YgXOR/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"gmZillaLandingPage"}
              data-plasmic-override={overrides.gmZillaLandingPage}
              className={classNames(projectcss.all, sty.gmZillaLandingPage)}
            >
              <div
                data-plasmic-name={"sunny1"}
                data-plasmic-override={overrides.sunny1}
                className={classNames(projectcss.all, sty.sunny1)}
              />

              <div
                data-plasmic-name={"rectangle11"}
                data-plasmic-override={overrides.rectangle11}
                className={classNames(projectcss.all, sty.rectangle11)}
              />

              <div
                data-plasmic-name={"rectangle16"}
                data-plasmic-override={overrides.rectangle16}
                className={classNames(projectcss.all, sty.rectangle16)}
              />

              {true ? (
                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                >
                  <Discord
                    data-plasmic-name={"discord"}
                    data-plasmic-override={overrides.discord}
                    className={classNames("__wab_instance", sty.discord)}
                  />
                </div>
              ) : null}

              <div
                data-plasmic-name={"frame"}
                data-plasmic-override={overrides.frame}
                className={classNames(projectcss.all, sty.frame)}
              >
                <div
                  data-plasmic-name={"group"}
                  data-plasmic-override={overrides.group}
                  className={classNames(projectcss.all, sty.group)}
                >
                  <div
                    data-plasmic-name={"layer1"}
                    data-plasmic-override={overrides.layer1}
                    className={classNames(projectcss.all, sty.layer1)}
                  >
                    <GroupIcon
                      className={classNames(projectcss.all, sty.svg__sWMta)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(projectcss.all, sty.group2)}
                    >
                      <VectorIcon
                        className={classNames(projectcss.all, sty.svg__oUdGt)}
                        role={"img"}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__rd7R)}
                        displayHeight={"144.263px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"143.23px"}
                        loading={"lazy"}
                        src={{
                          src: group26SdBYfIbR5H,
                          fullWidth: 143.23,
                          fullHeight: 144.263,
                          aspectRatio: 0.993103
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bLGk
                )}
              >
                {"Coming Soon..."}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4ZUhq
                )}
              >
                {"10,000 of 10,000 available"}
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"rectangle5"}
                  data-plasmic-override={overrides.rectangle5}
                  className={classNames(projectcss.all, sty.rectangle5)}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"cherryBlossom2021"}
                  data-plasmic-override={overrides.cherryBlossom2021}
                  className={classNames(projectcss.all, sty.cherryBlossom2021)}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"rectangle6"}
                  data-plasmic-override={overrides.rectangle6}
                  className={classNames(projectcss.all, sty.rectangle6)}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"group3"}
                  data-plasmic-override={overrides.group3}
                  className={classNames(projectcss.all, sty.group3)}
                >
                  <div
                    data-plasmic-name={"rectangle2"}
                    data-plasmic-override={overrides.rectangle2}
                    className={classNames(projectcss.all, sty.rectangle2)}
                  />

                  <div
                    data-plasmic-name={"group4"}
                    data-plasmic-override={overrides.group4}
                    className={classNames(projectcss.all, sty.group4)}
                  >
                    <div
                      data-plasmic-name={"group1"}
                      data-plasmic-override={overrides.group1}
                      className={classNames(projectcss.all, sty.group1)}
                    >
                      <div
                        data-plasmic-name={"preview11"}
                        data-plasmic-override={overrides.preview11}
                        className={classNames(projectcss.all, sty.preview11)}
                      />
                    </div>

                    <Ellipse3Icon
                      className={classNames(projectcss.all, sty.svg__nooa3)}
                      role={"img"}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nypHq
                    )}
                  >
                    {"GET YOUR"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gpwUo
                    )}
                  >
                    {"GMZillas"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d65F
                    )}
                  >
                    {
                      "GMZTA is a collection of 10,000 unique generated NFTs (0.05 ETH) launching in December on Ethereum Mainnet.\n\nOur Roadmap 1.0 consists of explosive utilities for GMZTA holders that will elevate your NFT experience and give every Genesis GMZilla holders exclusive access for future drops in our roadmap."
                    }
                  </div>

                  <div
                    data-plasmic-name={"rectangle4"}
                    data-plasmic-override={overrides.rectangle4}
                    className={classNames(projectcss.all, sty.rectangle4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5KsQ4
                      )}
                    >
                      {"Coming Soon..."}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"rectangle7"}
                    data-plasmic-override={overrides.rectangle7}
                    className={classNames(projectcss.all, sty.rectangle7)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wmniz
                    )}
                  >
                    {"10,000 of 10,000 available"}
                  </div>
                </div>
              ) : null}

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qBPlY
                )}
              >
                {"OUR TEAM"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ob7Kn
                )}
              >
                {"ROADMAP 1.0"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pyAAr
                )}
              >
                {"MomoJira"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gyvOc
                )}
              >
                {"Project Manager"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7NUjr
                )}
              >
                {"Gojiberri"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__quoPn
                )}
              >
                {"Marketing Lead"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aa9XR
                )}
              >
                {"GM Jira"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qiBlb
                )}
              >
                {"Business Developer"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qnOlZ
                )}
              >
                {"Macjira"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y1Tr
                )}
              >
                {"Full-stack Developer"}
              </div>

              <div
                data-plasmic-name={"group7"}
                data-plasmic-override={overrides.group7}
                className={classNames(projectcss.all, sty.group7)}
              >
                <div
                  data-plasmic-name={"image4"}
                  data-plasmic-override={overrides.image4}
                  className={classNames(projectcss.all, sty.image4)}
                />
              </div>

              <div
                data-plasmic-name={"rectangle8"}
                data-plasmic-override={overrides.rectangle8}
                className={classNames(projectcss.all, sty.rectangle8)}
              />

              <div
                data-plasmic-name={"group6"}
                data-plasmic-override={overrides.group6}
                className={classNames(projectcss.all, sty.group6)}
              >
                <div
                  data-plasmic-name={"image3"}
                  data-plasmic-override={overrides.image3}
                  className={classNames(projectcss.all, sty.image3)}
                />
              </div>

              <div
                data-plasmic-name={"rectangle9"}
                data-plasmic-override={overrides.rectangle9}
                className={classNames(projectcss.all, sty.rectangle9)}
              />

              <div
                data-plasmic-name={"group5"}
                data-plasmic-override={overrides.group5}
                className={classNames(projectcss.all, sty.group5)}
              >
                <div
                  data-plasmic-name={"image1"}
                  data-plasmic-override={overrides.image1}
                  className={classNames(projectcss.all, sty.image1)}
                />
              </div>

              <div
                data-plasmic-name={"rectangle10"}
                data-plasmic-override={overrides.rectangle10}
                className={classNames(projectcss.all, sty.rectangle10)}
              />

              <div
                data-plasmic-name={"group8"}
                data-plasmic-override={overrides.group8}
                className={classNames(projectcss.all, sty.group8)}
              >
                <div
                  data-plasmic-name={"image2"}
                  data-plasmic-override={overrides.image2}
                  className={classNames(projectcss.all, sty.image2)}
                />
              </div>

              <div
                data-plasmic-name={"rectangle12"}
                data-plasmic-override={overrides.rectangle12}
                className={classNames(projectcss.all, sty.rectangle12)}
              />

              <div
                data-plasmic-name={"rectangle14"}
                data-plasmic-override={overrides.rectangle14}
                className={classNames(projectcss.all, sty.rectangle14)}
              />

              <div
                data-plasmic-name={"group13"}
                data-plasmic-override={overrides.group13}
                className={classNames(projectcss.all, sty.group13)}
              >
                <div
                  data-plasmic-name={"group14"}
                  data-plasmic-override={overrides.group14}
                  className={classNames(projectcss.all, sty.group14)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__auTcp
                    )}
                  >
                    {"MINT"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jCzGg
                    )}
                  >
                    {"ROADMAP"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qrdle
                    )}
                  >
                    {"RANKING"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wnZoP
                    )}
                  >
                    {"FAQ"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bLj0
                    )}
                  >
                    {"TEAM"}
                  </div>
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__w2Nwh
                )}
              >
                {"CONNECT"}
              </div>

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__aLtcz)}
                role={"img"}
              />

              <Twitter
                data-plasmic-name={"twitter"}
                data-plasmic-override={overrides.twitter}
                className={classNames("__wab_instance", sty.twitter)}
              />

              <div
                data-plasmic-name={"_6011"}
                data-plasmic-override={overrides._6011}
                className={classNames(projectcss.all, sty._6011)}
              />

              <div
                data-plasmic-name={"group16"}
                data-plasmic-override={overrides.group16}
                className={classNames(projectcss.all, sty.group16)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ucTvc
                  )}
                >
                  {"PHASE 1"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0X7RQ
                  )}
                >
                  {
                    "- Presale spots for 500 OG Members\n- Contests and Giveaways (Additional 500 presale slots)\n- Auction of 10 Legendary GMZilla NFTs\n- Launch in December 2021 (Tentatively)"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group17"}
                data-plasmic-override={overrides.group17}
                className={classNames(projectcss.all, sty.group17)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ozVsJ
                  )}
                >
                  {"PHASE 2"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wX6UK
                  )}
                >
                  {
                    "- Rarity Sniper Rankings\n- Listed on Rarity Tools \n- GMZTA Limited Merch\n- Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group18"}
                data-plasmic-override={overrides.group18}
                className={classNames(projectcss.all, sty.group18)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v9FUs
                  )}
                >
                  {"PHASE 3"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c3Rqg
                  )}
                >
                  {
                    "- Aquire CryptoVoxel land for Community Activities\n- Proceeds of Legendary GMZilla Auction will bootstrap \n  $GTA token, and holders of every GMZTA NFT will \n  receive an airdrop, Tokenomics TBC\n- Sneak Peeks Into Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group19"}
                data-plasmic-override={overrides.group19}
                className={classNames(projectcss.all, sty.group19)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zHjwF
                  )}
                >
                  {"PHASE 4"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hO8X
                  )}
                >
                  {
                    "- 1000 Travel Tickets to be minted using $GTA\n- Aquire Sandbox Land for development\n- Hire voxel architect to build GMZilla VX Collection"
                  }
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7NjJe
                )}
              >
                {"AND MORE..."}
              </div>

              <div
                data-plasmic-name={"group15"}
                data-plasmic-override={overrides.group15}
                className={classNames(projectcss.all, sty.group15)}
              >
                <div
                  data-plasmic-name={"gmztaPreview1"}
                  data-plasmic-override={overrides.gmztaPreview1}
                  className={classNames(projectcss.all, sty.gmztaPreview1)}
                />
              </div>

              <Line3Icon
                className={classNames(projectcss.all, sty.svg___9QcS)}
                role={"img"}
              />

              <div
                data-plasmic-name={"group9"}
                data-plasmic-override={overrides.group9}
                className={classNames(projectcss.all, sty.group9)}
              >
                <div
                  data-plasmic-name={"layer2"}
                  data-plasmic-override={overrides.layer2}
                  className={classNames(projectcss.all, sty.layer2)}
                >
                  <Group4Icon
                    className={classNames(projectcss.all, sty.svg__lKb2S)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"group10"}
                    data-plasmic-override={overrides.group10}
                    className={classNames(projectcss.all, sty.group10)}
                  >
                    <Vector4Icon
                      className={classNames(projectcss.all, sty.svg___3JgzP)}
                      role={"img"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hidkd)}
                      displayHeight={"36.474px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"36.213px"}
                      loading={"lazy"}
                      src={{
                        src: group5M3ESpiRigix,
                        fullWidth: 36.213,
                        fullHeight: 36.474,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle15"}
                data-plasmic-override={overrides.rectangle15}
                className={classNames(projectcss.all, sty.rectangle15)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hb3G0
                )}
              >
                {"FAQ"}
              </div>

              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(projectcss.all, sty.rectangle17)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bc57W
                )}
              >
                {"Ser How?"}
              </div>

              <div
                data-plasmic-name={
                  "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
                }
                data-plasmic-override={
                  overrides.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats
                )}
              >
                {
                  "Set up your Metamask wallet, load up some ETH (with additional ETH for gas). Connect your wallet, select quantity and mint. Congrats!\n"
                }
              </div>

              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(projectcss.all, sty.rectangle18)}
              />

              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(projectcss.all, sty.rectangle19)}
              />

              <div
                data-plasmic-name={"rectangle20"}
                data-plasmic-override={overrides.rectangle20}
                className={classNames(projectcss.all, sty.rectangle20)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dDpBe
                )}
              >
                {"Wen?"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ur2Q1
                )}
              >
                {"How many GMZillas are out there?"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nmYml
                )}
              >
                {"Wut benefits are there for GMZilla holders?"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qk65
                )}
              >
                {
                  "Presale mint will begin on 22nd December at 7pm UTC (24hr window) and Public sale will begin on 23rd December at 7pm UTC."
                }
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hIKqe
                )}
              >
                {"There are total of 10,000 GMZillas to be minted."}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dsv0
                )}
              >
                {
                  "Please check our jam-packed roadmap and join our discord for juicy updates."
                }
              </div>

              <div
                data-plasmic-name={"rectangle21"}
                data-plasmic-override={overrides.rectangle21}
                className={classNames(projectcss.all, sty.rectangle21)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__a08Cy
                )}
              >
                {
                  "Each NFT is generated algorithmically with more than 150 hand drawn traits with varying rarity accross categories."
                }
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lijt4
                )}
              >
                {"RARITY"}
              </div>

              <div
                data-plasmic-name={"group20"}
                data-plasmic-override={overrides.group20}
                className={classNames(projectcss.all, sty.group20)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x8Jnn
                  )}
                >
                  {"Total GMZillas"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yaNms
                  )}
                >
                  {"10,000"}
                </div>
              </div>

              <div
                data-plasmic-name={"group21"}
                data-plasmic-override={overrides.group21}
                className={classNames(projectcss.all, sty.group21)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__omNGv
                  )}
                >
                  {"Backgrounds"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oTutR
                  )}
                >
                  {"Weather"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gGpme
                  )}
                >
                  {"Skins"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v2Dov
                  )}
                >
                  {"Outfit"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yfTeN
                  )}
                >
                  {"Headgear"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__imIcW
                  )}
                >
                  {"Eyewear"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m6CrY
                  )}
                >
                  {"Handheld"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Y3SF
                  )}
                >
                  {"Eyes"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hpQo
                  )}
                >
                  {"Mouth"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__clQo6
                  )}
                >
                  {"Plates"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__momwB
                  )}
                >
                  {"22"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__plmqh
                  )}
                >
                  {"6"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lfrL
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aqIcQ
                  )}
                >
                  {"10"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7JvjU
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Zt4B
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Ql7K
                  )}
                >
                  {"14"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yiYNq
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f1SRg
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h89XY
                  )}
                >
                  {"8"}
                </div>
              </div>

              <Line4Icon
                className={classNames(projectcss.all, sty.svg___9YwW)}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__axKkV)}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(projectcss.all, sty.svg__mlpU6)}
                role={"img"}
              />

              <Group3Icon
                className={classNames(projectcss.all, sty.svg__fdxu)}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__acxvb)}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(projectcss.all, sty.svg__kV4P)}
                role={"img"}
              />

              <Group3Icon
                className={classNames(projectcss.all, sty.svg__fIxep)}
                role={"img"}
              />

              <div
                data-plasmic-name={"group11"}
                data-plasmic-override={overrides.group11}
                className={classNames(projectcss.all, sty.group11)}
              >
                <div
                  data-plasmic-name={"layer3"}
                  data-plasmic-override={overrides.layer3}
                  className={classNames(projectcss.all, sty.layer3)}
                >
                  <Group6Icon
                    className={classNames(projectcss.all, sty.svg___4Byj3)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"group12"}
                    data-plasmic-override={overrides.group12}
                    className={classNames(projectcss.all, sty.group12)}
                  >
                    <Vector5Icon
                      className={classNames(projectcss.all, sty.svg__qgAn4)}
                      role={"img"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xKgo6)}
                      displayHeight={"24.903px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24.724px"}
                      loading={"lazy"}
                      src={{
                        src: group7Z1Vvgga4LAr,
                        fullWidth: 24.724,
                        fullHeight: 24.903,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"group27"}
                data-plasmic-override={overrides.group27}
                className={classNames(projectcss.all, sty.group27)}
              >
                <div
                  data-plasmic-name={"group22"}
                  data-plasmic-override={overrides.group22}
                  className={classNames(projectcss.all, sty.group22)}
                >
                  <div
                    data-plasmic-name={"image5"}
                    data-plasmic-override={overrides.image5}
                    className={classNames(projectcss.all, sty.image5)}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle22"}
                  data-plasmic-override={overrides.rectangle22}
                  className={classNames(projectcss.all, sty.rectangle22)}
                />
              </div>

              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(projectcss.all, sty.group26)}
              >
                <div
                  data-plasmic-name={"group23"}
                  data-plasmic-override={overrides.group23}
                  className={classNames(projectcss.all, sty.group23)}
                >
                  <div
                    data-plasmic-name={"image6"}
                    data-plasmic-override={overrides.image6}
                    className={classNames(projectcss.all, sty.image6)}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle23"}
                  data-plasmic-override={overrides.rectangle23}
                  className={classNames(projectcss.all, sty.rectangle23)}
                />
              </div>

              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(projectcss.all, sty.group25)}
              >
                <div
                  data-plasmic-name={"group24"}
                  data-plasmic-override={overrides.group24}
                  className={classNames(projectcss.all, sty.group24)}
                >
                  <div
                    data-plasmic-name={"image7"}
                    data-plasmic-override={overrides.image7}
                    className={classNames(projectcss.all, sty.image7)}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle24"}
                  data-plasmic-override={overrides.rectangle24}
                  className={classNames(projectcss.all, sty.rectangle24)}
                />
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"mobileVer"}
              data-plasmic-override={overrides.mobileVer}
              className={classNames(projectcss.all, sty.mobileVer)}
            >
              <div
                data-plasmic-name={"sunny2"}
                data-plasmic-override={overrides.sunny2}
                className={classNames(projectcss.all, sty.sunny2)}
              />

              <div className={classNames(projectcss.all, sty.freeBox__hM0X)} />

              <div className={classNames(projectcss.all, sty.freeBox__rXqFu)}>
                <div className={classNames(projectcss.all, sty.freeBox__sYnMn)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <Group8Icon
                      className={classNames(projectcss.all, sty.svg__pFmSi)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nkb5I)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Vector6Icon
                        className={classNames(projectcss.all, sty.svg__sxKFt)}
                        role={"img"}
                      />
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hZe57)}
                        displayHeight={"27.698px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"31.218px"}
                        loading={"lazy"}
                        src={{
                          src: group9Yl7EDl7Rtt,
                          fullWidth: 31.218,
                          fullHeight: 27.698,
                          aspectRatio: 1.142857
                        }}
                      />
                    ) : null}
                  </div>
                </div>
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Group866Icon
                  className={classNames(projectcss.all, sty.svg__vmuTz)}
                  role={"img"}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__rrsiR)} />

              <div
                className={classNames(projectcss.all, sty.freeBox___2Ury6)}
              />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__g4Muu)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__hwFiW)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__dx71I)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg___47BWw)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__tomp3)}
                  role={"img"}
                />
              ) : null}

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nt4KJ
                )}
              >
                {"ROADMAP 1.0"}
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__jwXRg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__srviR
                  )}
                >
                  {"PHASE 1"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qsonf
                  )}
                >
                  {
                    "- Presale spots for 500 OG Members\n- Contests and Giveaways \n(Additional 500 presale slots)\n- Auction of 10 Legendary GMZilla NFTs\n- Launch in December 2021 (Tentatively)"
                  }
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__lc708)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p8Nb9
                  )}
                >
                  {"PHASE 2"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___26XNf
                  )}
                >
                  {
                    "- Rarity Sniper Rankings\n- Listed on Rarity Tools \n- GMZTA Limited Merch\n- Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox___41U1W)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h8QhZ
                  )}
                >
                  {"PHASE 3"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hpa2R
                  )}
                >
                  {
                    "- Aquire CryptoVoxel land for Community Activities\n- Proceeds of Legendary GMZilla Auction will bootstrap $GTA token, and holders of every GMZTA NFT will receive an airdrop, Tokenomics TBC\n- Sneak Peeks Into Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox___41AyD)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zea5J
                  )}
                >
                  {"PHASE 4"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__coMEt
                  )}
                >
                  {
                    "- 1000 Travel Tickets to be minted using $GTA\n- Aquire Sandbox Land for development\n- Hire voxel architect to build GMZilla VX Collection"
                  }
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__st7OQ
                )}
              >
                {"AND MORE..."}
              </div>

              {true ? (
                <div
                  data-plasmic-name={"cherryBlossom2022"}
                  data-plasmic-override={overrides.cherryBlossom2022}
                  className={classNames(projectcss.all, sty.cherryBlossom2022)}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__d3Pwf)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__deqtP)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__yuf30)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jqHi3)}
                  >
                    <div
                      data-plasmic-name={"preview12"}
                      data-plasmic-override={overrides.preview12}
                      className={classNames(projectcss.all, sty.preview12)}
                    />
                  </div>

                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <Ellipse5Icon
                      className={classNames(projectcss.all, sty.svg__kKiF)}
                      role={"img"}
                    />
                  ) : null}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nkEvo
                  )}
                >
                  {"GET YOUR"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cZwdV
                  )}
                >
                  {"GMZillas"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h6Ura
                  )}
                >
                  {
                    "GMZTA is a collection of 10,000 unique generated NFTs (0.05 ETH) launching in December on Ethereum Mainnet.\n\nOur Roadmap 1.0 consists of explosive utilities for GMZTA holders that will elevate your NFT experience and give every Genesis GMZilla holders exclusive access for future drops in our roadmap."
                  }
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox___3XHKe)}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__g9QXm)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4MbDx
                  )}
                >
                  {"Coming Soon..."}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gdijD
                  )}
                >
                  {"10,000 of 10,000 available"}
                </div>
              </div>

              <div
                data-plasmic-name={"frame2"}
                data-plasmic-override={overrides.frame2}
                className={classNames(projectcss.all, sty.frame2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox___7S2F)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zfP2Q)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Group10Icon
                        className={classNames(projectcss.all, sty.svg__ho3Gz)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(projectcss.all, sty.freeBox__yjy1T)}
                    >
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Vector7Icon
                          className={classNames(projectcss.all, sty.svg__ylJKp)}
                          role={"img"}
                        />
                      ) : null}
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__dIjfc)}
                          displayHeight={"69.917px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"69.417px"}
                          loading={"lazy"}
                          src={{
                            src: group11JnCwAzfbeiS,
                            fullWidth: 69.417,
                            fullHeight: 69.917,
                            aspectRatio: 1
                          }}
                        />
                      ) : null}
                    </div>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__mrWzA)} />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gV5Db
                )}
              >
                {"Coming Soon..."}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u3CxE
                )}
              >
                {"10,000 of 10,000 available"}
              </div>

              <div className={classNames(projectcss.all, sty.freeBox___4Il6Y)}>
                <div
                  data-plasmic-name={"gmztaPreview2"}
                  data-plasmic-override={overrides.gmztaPreview2}
                  className={classNames(projectcss.all, sty.gmztaPreview2)}
                />
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__x6TDo)} />

              <div className={classNames(projectcss.all, sty.freeBox__zVaw1)} />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nTnK
                )}
              >
                {"RARITY"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ukCs
                )}
              >
                {
                  "Each NFT is generated algorithmically with more than 150 hand drawn traits with varying rarity accross categories."
                }
              </div>

              <div className={classNames(projectcss.all, sty.freeBox___9Yhfw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l9F4G
                  )}
                >
                  {"Total GMZillas"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kjebp
                  )}
                >
                  {"10,000"}
                </div>
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line8Icon
                  className={classNames(projectcss.all, sty.svg__sdUEz)}
                  role={"img"}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__vAlSa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r77Ks
                  )}
                >
                  {"Backgrounds"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0GmyL
                  )}
                >
                  {"Weather"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rzCv
                  )}
                >
                  {"Skins"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7T8XJ
                  )}
                >
                  {"Outfit"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9Xhsu
                  )}
                >
                  {"Plates"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__at8Ha
                  )}
                >
                  {"22"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oFJdH
                  )}
                >
                  {"6"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fqv5Z
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xxooq
                  )}
                >
                  {"10"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zRuzA
                  )}
                >
                  {"8"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__qlo9S)} />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rsNui
                )}
              >
                {"OUR TEAM"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame863"}
                data-plasmic-override={overrides.frame863}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame863)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame859"}
                  data-plasmic-override={overrides.frame859}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame859)}
                >
                  <div
                    data-plasmic-name={"group873"}
                    data-plasmic-override={overrides.group873}
                    className={classNames(projectcss.all, sty.group873)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fR4Qq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fqF7Q
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__hUWlx)}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mAsMp
                    )}
                  >
                    {"MomoJira"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cScTl
                    )}
                  >
                    {"Project Manager"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame860"}
                  data-plasmic-override={overrides.frame860}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame860)}
                >
                  <div
                    data-plasmic-name={"group874"}
                    data-plasmic-override={overrides.group874}
                    className={classNames(projectcss.all, sty.group874)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__udNLz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9L0W7
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__xZ11S)}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yz4Tt
                    )}
                  >
                    {"Gojiberri"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kpUxg
                    )}
                  >
                    {"Marketing Lead"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame861"}
                  data-plasmic-override={overrides.frame861}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame861)}
                >
                  <div
                    data-plasmic-name={"group875"}
                    data-plasmic-override={overrides.group875}
                    className={classNames(projectcss.all, sty.group875)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mFoP5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ldWGt
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__iQpA)}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pl5OH
                    )}
                  >
                    {"GM Jira"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d1J0K
                    )}
                  >
                    {"Business Developer"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame862"}
                  data-plasmic-override={overrides.frame862}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame862)}
                >
                  <div
                    data-plasmic-name={"group876"}
                    data-plasmic-override={overrides.group876}
                    className={classNames(projectcss.all, sty.group876)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kkZzg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yP2MY
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__th1ST)}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2S9Tu
                    )}
                  >
                    {"Macjira"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5FLa5
                    )}
                  >
                    {"Full-stack Developer"}
                  </div>
                </p.Stack>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__i20Wt)} />

              <div
                data-plasmic-name={"_6012"}
                data-plasmic-override={overrides._6012}
                className={classNames(projectcss.all, sty._6012)}
              />

              <div className={classNames(projectcss.all, sty.freeBox__liecG)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wx4VP
                  )}
                >
                  {"Headgear"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tiEgK
                  )}
                >
                  {"Eyewear"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bj9Pb
                  )}
                >
                  {"Handheld"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__an4Rn
                  )}
                >
                  {"Eyes"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r7Zdh
                  )}
                >
                  {"Mouth"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w5WL
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xeJdm
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___78Vuf
                  )}
                >
                  {"14"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kyW9
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ocaP7
                  )}
                >
                  {"12"}
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xbIm
                )}
              >
                {"FAQ"}
              </div>

              <div
                data-plasmic-name={"group880"}
                data-plasmic-override={overrides.group880}
                className={classNames(projectcss.all, sty.group880)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__m8XmV)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iKa8S
                  )}
                >
                  {"Ser How?"}
                </div>

                <div
                  data-plasmic-name={
                    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2"
                  }
                  data-plasmic-override={
                    overrides.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2
                  )}
                >
                  {
                    "Set up your Metamask wallet, load up some ETH (with additional ETH for gas). Connect your wallet, select quantity and mint. Congrats!\n"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group877"}
                data-plasmic-override={overrides.group877}
                className={classNames(projectcss.all, sty.group877)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__wAqny)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___944Y
                  )}
                >
                  {"Wen?"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wWhgv
                  )}
                >
                  {
                    "Presale mint will begin on 22nd December at 7pm UTC (24hr window) and Public sale will begin on 23rd December at 7pm UTC."
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group878"}
                data-plasmic-override={overrides.group878}
                className={classNames(projectcss.all, sty.group878)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__dfM4I)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gOdrv
                  )}
                >
                  {"How many GMZillas are out there?"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hZzm3
                  )}
                >
                  {"There are total of 10,000 GMZillas to be minted."}
                </div>
              </div>

              <div
                data-plasmic-name={"group879"}
                data-plasmic-override={overrides.group879}
                className={classNames(projectcss.all, sty.group879)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__kUIm)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p63CR
                  )}
                >
                  {"Wut benefits are there for GMZilla holders?"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gOuYo
                  )}
                >
                  {
                    "Please check our jam-packed roadmap and join our discord for juicy updates."
                  }
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__zCzXs)} />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame864"}
                data-plasmic-override={overrides.frame864}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame864)}
              >
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Vector8Icon
                    className={classNames(projectcss.all, sty.svg__qGpWw)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Group12Icon
                    className={classNames(projectcss.all, sty.svg__zOnP1)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Vector9Icon
                    className={classNames(projectcss.all, sty.svg__xqLbs)}
                    role={"img"}
                  />
                ) : null}
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__rDrRl)}>
                <div className={classNames(projectcss.all, sty.freeBox__wbJll)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <Group13Icon
                      className={classNames(projectcss.all, sty.svg__xzQu)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox___2WOf8)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Vector10Icon
                        className={classNames(projectcss.all, sty.svg__p1JQb)}
                        role={"img"}
                      />
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__m4B4T)}
                        displayHeight={"31.253px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"31.03px"}
                        loading={"lazy"}
                        src={{
                          src: group14ExUhI5YgXor,
                          fullWidth: 31.03,
                          fullHeight: 31.253,
                          aspectRatio: 1
                        }}
                      />
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          ) : null}
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "gmZillaLandingPage",
    "sunny1",
    "rectangle11",
    "rectangle16",
    "rectangle1",
    "discord",
    "frame",
    "group",
    "layer1",
    "group2",
    "rectangle3",
    "rectangle5",
    "rectangle13",
    "cherryBlossom2021",
    "rectangle6",
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7",
    "group7",
    "image4",
    "rectangle8",
    "group6",
    "image3",
    "rectangle9",
    "group5",
    "image1",
    "rectangle10",
    "group8",
    "image2",
    "rectangle12",
    "rectangle14",
    "group13",
    "group14",
    "twitter",
    "_6011",
    "group16",
    "group17",
    "group18",
    "group19",
    "group15",
    "gmztaPreview1",
    "group9",
    "layer2",
    "group10",
    "rectangle15",
    "rectangle17",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "group20",
    "group21",
    "group11",
    "layer3",
    "group12",
    "group27",
    "group22",
    "image5",
    "rectangle22",
    "group26",
    "group23",
    "image6",
    "rectangle23",
    "group25",
    "group24",
    "image7",
    "rectangle24",
    "mobileVer",
    "sunny2",
    "cherryBlossom2022",
    "preview12",
    "frame2",
    "gmztaPreview2",
    "frame863",
    "frame859",
    "group873",
    "frame860",
    "group874",
    "frame861",
    "group875",
    "frame862",
    "group876",
    "_6012",
    "group880",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2",
    "group877",
    "group878",
    "group879",
    "frame864"
  ],

  gmZillaLandingPage: [
    "gmZillaLandingPage",
    "sunny1",
    "rectangle11",
    "rectangle16",
    "rectangle1",
    "discord",
    "frame",
    "group",
    "layer1",
    "group2",
    "rectangle3",
    "rectangle5",
    "rectangle13",
    "cherryBlossom2021",
    "rectangle6",
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7",
    "group7",
    "image4",
    "rectangle8",
    "group6",
    "image3",
    "rectangle9",
    "group5",
    "image1",
    "rectangle10",
    "group8",
    "image2",
    "rectangle12",
    "rectangle14",
    "group13",
    "group14",
    "twitter",
    "_6011",
    "group16",
    "group17",
    "group18",
    "group19",
    "group15",
    "gmztaPreview1",
    "group9",
    "layer2",
    "group10",
    "rectangle15",
    "rectangle17",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "group20",
    "group21",
    "group11",
    "layer3",
    "group12",
    "group27",
    "group22",
    "image5",
    "rectangle22",
    "group26",
    "group23",
    "image6",
    "rectangle23",
    "group25",
    "group24",
    "image7",
    "rectangle24"
  ],

  sunny1: ["sunny1"],
  rectangle11: ["rectangle11"],
  rectangle16: ["rectangle16"],
  rectangle1: ["rectangle1", "discord"],
  discord: ["discord"],
  frame: ["frame", "group", "layer1", "group2"],
  group: ["group", "layer1", "group2"],
  layer1: ["layer1", "group2"],
  group2: ["group2"],
  rectangle3: ["rectangle3"],
  rectangle5: ["rectangle5"],
  rectangle13: ["rectangle13"],
  cherryBlossom2021: ["cherryBlossom2021"],
  rectangle6: ["rectangle6"],
  group3: [
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7"
  ],

  rectangle2: ["rectangle2"],
  group4: ["group4", "group1", "preview11"],
  group1: ["group1", "preview11"],
  preview11: ["preview11"],
  rectangle4: ["rectangle4"],
  rectangle7: ["rectangle7"],
  group7: ["group7", "image4"],
  image4: ["image4"],
  rectangle8: ["rectangle8"],
  group6: ["group6", "image3"],
  image3: ["image3"],
  rectangle9: ["rectangle9"],
  group5: ["group5", "image1"],
  image1: ["image1"],
  rectangle10: ["rectangle10"],
  group8: ["group8", "image2"],
  image2: ["image2"],
  rectangle12: ["rectangle12"],
  rectangle14: ["rectangle14"],
  group13: ["group13", "group14"],
  group14: ["group14"],
  twitter: ["twitter"],
  _6011: ["_6011"],
  group16: ["group16"],
  group17: ["group17"],
  group18: ["group18"],
  group19: ["group19"],
  group15: ["group15", "gmztaPreview1"],
  gmztaPreview1: ["gmztaPreview1"],
  group9: ["group9", "layer2", "group10"],
  layer2: ["layer2", "group10"],
  group10: ["group10"],
  rectangle15: ["rectangle15"],
  rectangle17: ["rectangle17"],
  setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats:
    [
      "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
    ],

  rectangle18: ["rectangle18"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  group20: ["group20"],
  group21: ["group21"],
  group11: ["group11", "layer3", "group12"],
  layer3: ["layer3", "group12"],
  group12: ["group12"],
  group27: ["group27", "group22", "image5", "rectangle22"],
  group22: ["group22", "image5"],
  image5: ["image5"],
  rectangle22: ["rectangle22"],
  group26: ["group26", "group23", "image6", "rectangle23"],
  group23: ["group23", "image6"],
  image6: ["image6"],
  rectangle23: ["rectangle23"],
  group25: ["group25", "group24", "image7", "rectangle24"],
  group24: ["group24", "image7"],
  image7: ["image7"],
  rectangle24: ["rectangle24"],
  mobileVer: [
    "mobileVer",
    "sunny2",
    "cherryBlossom2022",
    "preview12",
    "frame2",
    "gmztaPreview2",
    "frame863",
    "frame859",
    "group873",
    "frame860",
    "group874",
    "frame861",
    "group875",
    "frame862",
    "group876",
    "_6012",
    "group880",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2",
    "group877",
    "group878",
    "group879",
    "frame864"
  ],

  sunny2: ["sunny2"],
  cherryBlossom2022: ["cherryBlossom2022"],
  preview12: ["preview12"],
  frame2: ["frame2"],
  gmztaPreview2: ["gmztaPreview2"],
  frame863: [
    "frame863",
    "frame859",
    "group873",
    "frame860",
    "group874",
    "frame861",
    "group875",
    "frame862",
    "group876"
  ],

  frame859: ["frame859", "group873"],
  group873: ["group873"],
  frame860: ["frame860", "group874"],
  group874: ["group874"],
  frame861: ["frame861", "group875"],
  group875: ["group875"],
  frame862: ["frame862", "group876"],
  group876: ["group876"],
  _6012: ["_6012"],
  group880: [
    "group880",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2"
  ],

  setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2:
    [
      "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2"
    ],

  group877: ["group877"],
  group878: ["group878"],
  group879: ["group879"],
  frame864: ["frame864"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    gmZillaLandingPage: makeNodeComponent("gmZillaLandingPage"),
    sunny1: makeNodeComponent("sunny1"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle16: makeNodeComponent("rectangle16"),
    rectangle1: makeNodeComponent("rectangle1"),
    discord: makeNodeComponent("discord"),
    frame: makeNodeComponent("frame"),
    group: makeNodeComponent("group"),
    layer1: makeNodeComponent("layer1"),
    group2: makeNodeComponent("group2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle13: makeNodeComponent("rectangle13"),
    cherryBlossom2021: makeNodeComponent("cherryBlossom2021"),
    rectangle6: makeNodeComponent("rectangle6"),
    group3: makeNodeComponent("group3"),
    rectangle2: makeNodeComponent("rectangle2"),
    group4: makeNodeComponent("group4"),
    group1: makeNodeComponent("group1"),
    preview11: makeNodeComponent("preview11"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle7: makeNodeComponent("rectangle7"),
    group7: makeNodeComponent("group7"),
    image4: makeNodeComponent("image4"),
    rectangle8: makeNodeComponent("rectangle8"),
    group6: makeNodeComponent("group6"),
    image3: makeNodeComponent("image3"),
    rectangle9: makeNodeComponent("rectangle9"),
    group5: makeNodeComponent("group5"),
    image1: makeNodeComponent("image1"),
    rectangle10: makeNodeComponent("rectangle10"),
    group8: makeNodeComponent("group8"),
    image2: makeNodeComponent("image2"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle14: makeNodeComponent("rectangle14"),
    group13: makeNodeComponent("group13"),
    group14: makeNodeComponent("group14"),
    twitter: makeNodeComponent("twitter"),
    _6011: makeNodeComponent("_6011"),
    group16: makeNodeComponent("group16"),
    group17: makeNodeComponent("group17"),
    group18: makeNodeComponent("group18"),
    group19: makeNodeComponent("group19"),
    group15: makeNodeComponent("group15"),
    gmztaPreview1: makeNodeComponent("gmztaPreview1"),
    group9: makeNodeComponent("group9"),
    layer2: makeNodeComponent("layer2"),
    group10: makeNodeComponent("group10"),
    rectangle15: makeNodeComponent("rectangle15"),
    rectangle17: makeNodeComponent("rectangle17"),
    setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats:
      makeNodeComponent(
        "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
      ),

    rectangle18: makeNodeComponent("rectangle18"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    group21: makeNodeComponent("group21"),
    group11: makeNodeComponent("group11"),
    layer3: makeNodeComponent("layer3"),
    group12: makeNodeComponent("group12"),
    group27: makeNodeComponent("group27"),
    group22: makeNodeComponent("group22"),
    image5: makeNodeComponent("image5"),
    rectangle22: makeNodeComponent("rectangle22"),
    group26: makeNodeComponent("group26"),
    group23: makeNodeComponent("group23"),
    image6: makeNodeComponent("image6"),
    rectangle23: makeNodeComponent("rectangle23"),
    group25: makeNodeComponent("group25"),
    group24: makeNodeComponent("group24"),
    image7: makeNodeComponent("image7"),
    rectangle24: makeNodeComponent("rectangle24"),
    mobileVer: makeNodeComponent("mobileVer"),
    sunny2: makeNodeComponent("sunny2"),
    cherryBlossom2022: makeNodeComponent("cherryBlossom2022"),
    preview12: makeNodeComponent("preview12"),
    frame2: makeNodeComponent("frame2"),
    gmztaPreview2: makeNodeComponent("gmztaPreview2"),
    frame863: makeNodeComponent("frame863"),
    frame859: makeNodeComponent("frame859"),
    group873: makeNodeComponent("group873"),
    frame860: makeNodeComponent("frame860"),
    group874: makeNodeComponent("group874"),
    frame861: makeNodeComponent("frame861"),
    group875: makeNodeComponent("group875"),
    frame862: makeNodeComponent("frame862"),
    group876: makeNodeComponent("group876"),
    _6012: makeNodeComponent("_6012"),
    group880: makeNodeComponent("group880"),
    setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2:
      makeNodeComponent(
        "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats2"
      ),

    group877: makeNodeComponent("group877"),
    group878: makeNodeComponent("group878"),
    group879: makeNodeComponent("group879"),
    frame864: makeNodeComponent("frame864"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
